dataset:
  val:
  - name: skyscenes
    disp_name: skyscenes
    dir: /mnt/data/Skyscene/
    filenames: /mnt/data/bientd/Marigold/data_split/skyscenes/skyscenes_test.txt
    resize_to_hw:
    - 640
    - 480